# Generated by Django 5.2.16 on 2026-07-08 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('com_port', models.CharField(blank=True, default='', max_length=50)),
                ('baud_rate', models.IntegerField(default=115200)),
                ('theme', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark')], default='DARK', max_length=10)),
                ('auto_refresh_enabled', models.BooleanField(default=True)),
                ('auto_refresh_interval_seconds', models.PositiveIntegerField(default=5)),
                ('co2_warning', models.FloatField(default=1000)),
                ('co2_critical', models.FloatField(default=1500)),
                ('temp_warning', models.FloatField(default=28)),
                ('temp_critical', models.FloatField(default=35)),
                ('humidity_high_warning', models.FloatField(default=70)),
                ('humidity_high_critical', models.FloatField(default=85)),
                ('humidity_low_warning', models.FloatField(default=30)),
                ('humidity_low_critical', models.FloatField(default=20)),
                ('pm25_warning', models.FloatField(default=25)),
                ('pm25_critical', models.FloatField(default=75)),
                ('pm10_warning', models.FloatField(default=50)),
                ('pm10_critical', models.FloatField(default=150)),
                ('aqi_warning', models.FloatField(default=100)),
                ('aqi_critical', models.FloatField(default=150)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
