# Generated by Django 5.2.16 on 2026-07-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='co_critical',
            field=models.FloatField(default=35),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='co_warning',
            field=models.FloatField(default=9),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='voc_critical',
            field=models.FloatField(default=300),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='voc_warning',
            field=models.FloatField(default=150),
        ),
    ]
