# Generated by Django 5.2.16 on 2026-07-08 10:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('sensor_type', models.CharField(choices=[('CO2', 'CO2'), ('TEMPERATURE', 'Temperature'), ('HUMIDITY', 'Humidity'), ('PM25', 'PM2.5'), ('PM10', 'PM10'), ('PRESSURE', 'Pressure'), ('MULTI', 'Multi-parameter (all-in-one)')], default='MULTI', max_length=20)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('FAULT', 'Fault')], default='ONLINE', max_length=20)),
                ('last_calibrated', models.DateField(blank=True, null=True)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors_created', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='stations.station')),
            ],
            options={
                'db_table': 'sensors',
                'ordering': ['station__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('co2_ppm', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pressure', models.FloatField()),
                ('aqi_score', models.FloatField(blank=True, null=True)),
                ('alert_level', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('MODERATE', 'Moderate'), ('POOR', 'Poor'), ('VERY_POOR', 'Very Poor'), ('HAZARDOUS', 'Hazardous')], max_length=20, null=True)),
                ('fan_state', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='sensors.sensor')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='stations.station')),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.CharField(help_text='e.g. CO2, PM2.5, HUMIDITY', max_length=30)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('recommendation', models.CharField(blank=True, max_length=255)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stations.station')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensorreading')),
            ],
            options={
                'db_table': 'alert_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['timestamp'], name='sensor_read_timesta_56e803_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['station', 'timestamp'], name='sensor_read_station_ddc6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['alert_level'], name='sensor_read_alert_l_9cca33_idx'),
        ),
    ]
