# Generated by Django 5.2.16 on 2026-07-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='co_ppm',
            field=models.FloatField(default=0.0, help_text='Carbon monoxide, parts per million.'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='voc_index',
            field=models.FloatField(default=0.0, help_text='Volatile organic compound index (0-500 scale).'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('CO2', 'CO2'), ('CO', 'Carbon Monoxide'), ('VOC', 'VOC'), ('TEMPERATURE', 'Temperature'), ('HUMIDITY', 'Humidity'), ('PM25', 'PM2.5'), ('PM10', 'PM10'), ('PRESSURE', 'Pressure'), ('MULTI', 'Multi-parameter (all-in-one)')], default='MULTI', max_length=20),
        ),
    ]
