# Generated by Django 6.0.7 on 2026-08-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensorreading_co_ppm_sensorreading_voc_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='mq135_raw',
            field=models.IntegerField(default=0, help_text='Raw ADC value from MQ135 sensor (0-4095).'),
        ),
    ]
